---

freefeed_hostname: entire.vc
freefeed_media_hostname: media.entire.vc
freefeed_env: release
freefeed_s3_endpoint: ams3.digitaloceanspaces.com
freefeed_s3_bucket: entire-vc-media
freefeed_storage_type: s3
freefeed_base_port: 3000
freefeed_jobs_enabled: true
react_client_enabled: true
react_client_hostname: entire.vc
client_blue_port: 8080
client_green_port: 8081

auth_token_prefix: entirevc

# gateway on freefeed docker network
postgres_host: 172.18.0.1
postgres_port: 5432
postgres_user: freefeed
postgres_dbname: freefeed
postgres_textsearch_config: russian

monitor_prefix: entire-vc
freefeed_external_auth_providers_enabled: true
redis_host: "redis-{{ freefeed_env }}"
freefeed_server_instances: 2
freefeed_frontend_scheme: http

ansible_python_interpreter: /usr/bin/python3

freefeed_server_version: latest
react_client_version: latest
