- hosts: all
  become: yes
  vars:
    pepyatka_deploy_log_dir: /var/log/pepyatka-deploy
  tasks:
    - name: Clone pepyatka-ansible
      git:
        repo: "{{ pepyatka_ansible_repo }}"
        dest: /root/pepyatka-ansible
        version: "{{ pepyatka_ansible_branch }}"
        force: yes

    - name: Clone pepyatka-server
      git:
        repo: "{{ pepyatka_server_repo }}"
        dest: /root/pepyatka-server
        version: "{{ pepyatka_server_branch }}"
        force: yes

    - name: Clone react-client
      git:
        repo: "{{ react_client_repo }}"
        dest: /root/react-client
        version: "{{ react_client_branch }}"
        force: yes

    - name: Clone vanilla
      git:
        repo: "{{ vanilla_repo }}"
        dest: /root/vanilla
        version: "{{ vanilla_branch }}"
        force: yes
      when: vanilla_enabled

    - name: Copy vault password file
      copy: src="{{ vault_password_file }}" dest=/root/pepyatka.vault
      when: vault_password_file is defined

    - name: Deploy check-deploy script
      template: src=check-deploy.j2 dest=/root/check-deploy mode=0700

    - name: Deploy inventory for check-deploy script
      copy:
        src="../{{ pepyatka_deploy_inventory }}"
        dest="/root/pepyatka-ansible/{{ pepyatka_deploy_inventory }}"

    - name: Create directory for check-deploy logs
      file: path="{{ pepyatka_deploy_log_dir }}" state=directory

    - name: Setup logrotate for check-deploy logs
      template: src=check-deploy.logrotate.j2 dest=/etc/logrotate.d/check-deploy

    - name: Setup cron job for check-deploy
      cron:
        name="Deploy pepyatka"
        cron_file=check-deploy
        job=/root/check-deploy
        user=root
        minute="*/5"
        state=present

